# Use the official Dart image
FROM cirrusci/flutter:stable

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Get dependencies
RUN flutter pub get

RUN chmod -R 755 /app

# Expose the port the app runs on
EXPOSE 8080

# Run the application
CMD ["flutter", "run", "-d", "web-server", "--web-port", "8080"]



